### ISSUE TITLE
don't force state to be an object

### ISSUE THREAD

**Issue by conorhastings** [tkh44/smitty#1]
There are use cases for intiial state as things like Immutable objects, Maps, etc..., forcing {} makes api smitty flexible, I'll be happy to PR if you agree.

**Comment by developit** [comment]
I think it supports any value? I might be missing something.

**Comment by conorhastings** [comment]
must have changed around the time i made the issue https://github.com/tkh44/smitty/blob/8936c81bfa12e5ac300b66e369e783ee0a79271e/src/index.js#L4

initially was doing Object.assign on creation

**Comment by developit** [comment]
Ahh sweet.

**Comment by tkh44** [comment]
@conorhastings I realized this yesterday as well 👍 I'm going to make a new release right now with the update included.

**Comment by tkh44** [comment]
Fix is published in `v0.2.0`
