### ISSUE TITLE
Usage with spread opperator

### ISSUE THREAD

**Issue by IljaDaderko** [tkh44/smitty#2]
Hi,

I've tried to use spread operator as opposed to object assign in my reducer, however it doesn't seem to work:

```
router.addReducer({
  'router/SET_UP': (state, e) => ({
    ...state,
    transtionTo: e.transitionTo
  })
});
```

yet

```
router.addReducer({
  'router/SET_UP': (state, e) => {
    return Object.assign({}, state, { count: state.transitionTo + e.transitionTo });
  }
});
```

not entirely sure why. In terms of babel presets I was running redux with spread operators no problem before.

**Comment by tkh44** [comment]
That is interesting. Do you happen to have the transpiled code that I could see?

**Comment by tkh44** [comment]
It seems to be working fine for me here http://codepen.io/tkh44/pen/qRrQPZ?editors=0010#0. You may not be returning your state in one of your reducers. I've added a warning for that in `0.2.0`.
