### ISSUE TITLE
[Advice needed] on triggering re-render of components when state changes

### ISSUE THREAD

**Issue by IljaDaderko** [tkh44/smitty#6]
I'm loving emitter based state management via smitty so far. My biggest roadblock at the moment is that I can't simply do something like

```
<Component amount={amount.state.value} />
```

and expect `Component` to update when `value` changes, like we could via redux props. At the moment I need to use `state` and add a lot of `amount.on(SOMETHING)` listeners that then call functions to update that state hence re-rendering component with new values. Furthermore I need to remember to always do `amount.off` during un-mounting.

This brings me to reason behind this question. Can you advise what could be done here in order to achieve this i.e. something like `mapStateToProps` but using smitty?

**Comment by tkh44** [comment]
Yea, check out https://github.com/tkh44/react-smitty or https://github.com/tkh44/preact-smitty

Here is an example.
http://codepen.io/tkh44/pen/qRjjwb

```javascript
const mapStateToProps = (state) => ({ ui: state.get('ui') })
const Demo = connect(mapStateToProps)(({ ui, emit }) => {
  return h(
    'div',
    {
      className: 'demo',
      style: {
        height: '100%',
				color: ui.get('color'),
				background: ui.get('background'),
				WebkitFilter: `hue-rotate(${ui.get('hueRotate') % 360}deg)`
      }
    },
    h(Header, { emit }),
    h(Body, { ui, emit })
  )
})
```

It is listed in the docs but I should probably make it more prominent.

**Comment by IljaDaderko** [comment]
Ah that does the trick, missed it in documentation. Thank you :)
